//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phoenixtranslate.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Deepl</string>\r\n  <string>Google</string>\r\n  <string>Yandex</string>\r\n</Ar" +
            "rayOfString>")]
        public global::System.Collections.Specialized.StringCollection Name_Translator {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Name_Translator"]));
            }
            set {
                this["Name_Translator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>https://www.deepl.com/translator</string>
  <string>https://translate.google.com/</string>
  <string>https://translate.yandex.com/</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Link {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Link"]));
            }
            set {
                this["Link"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>/html[1]/body[1]/div[2]/div[1]/div[1]/div[3]/div[2]/div[1]/textarea[1]</string>
  <string>/html/body/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div/div/div[1]/textarea</string>
  <string>/html[1]/body[1]/div[2]/div[2]/div[1]/div[2]/div[1]/textarea[1]</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Xpathsender {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Xpathsender"]));
            }
            set {
                this["Xpathsender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>/html[1]/body[1]/div[2]/div[1]/div[1]/div[4]/div[3]/div[1]/textarea[1]</string>
  <string>/html[1]/body[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[3]/div[1]/div[2]/div[1]</string>
  <string>/html[1]/body[1]/div[2]/div[2]/div[2]/div[2]/div[1]/pre[1]</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Xpathreceiver {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Xpathreceiver"]));
            }
            set {
                this["Xpathreceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int index {
            get {
                return ((int)(this["index"]));
            }
            set {
                this["index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>#dl_translator &gt; div.lmt__sides_container &gt; div.lmt__side_container.lmt__side_container--source &gt; div.lmt__textarea_container &gt; div &gt; textarea</string>
  <string>#source</string>
  <string>#fakeArea</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Querysender {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Querysender"]));
            }
            set {
                this["Querysender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ParameterTag {
            get {
                return ((bool)(this["ParameterTag"]));
            }
            set {
                this["ParameterTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>af</string>\r\n  <string>sq</string>\r\n  <string>am</string>\r\n  <string>ar</s" +
            "tring>\r\n  <string>hy</string>\r\n  <string>az</string>\r\n  <string>eu</string>\r\n  <" +
            "string>be</string>\r\n  <string>bn</string>\r\n  <string>bs</string>\r\n  <string>bg</" +
            "string>\r\n  <string>ca</string>\r\n  <string>ceb</string>\r\n  <string>ny</string>\r\n " +
            " <string>zh-CN</string>\r\n  <string>co</string>\r\n  <string>hr</string>\r\n  <string" +
            ">cs</string>\r\n  <string>da</string>\r\n  <string>nl</string>\r\n  <string>en</string" +
            ">\r\n  <string>eo</string>\r\n  <string>et</string>\r\n  <string>tl</string>\r\n  <strin" +
            "g>fi</string>\r\n  <string>fr</string>\r\n  <string>fy</string>\r\n  <string>gl</strin" +
            "g>\r\n  <string>ka</string>\r\n  <string>de</string>\r\n  <string>el</string>\r\n  <stri" +
            "ng>gu</string>\r\n  <string>ht</string>\r\n  <string>ha</string>\r\n  <string>haw</str" +
            "ing>\r\n  <string>iw</string>\r\n  <string>hi</string>\r\n  <string>hmn</string>\r\n  <s" +
            "tring>hu</string>\r\n  <string>is</string>\r\n  <string>ig</string>\r\n  <string>id</s" +
            "tring>\r\n  <string>ga</string>\r\n  <string>it</string>\r\n  <string>ja</string>\r\n  <" +
            "string>jw</string>\r\n  <string>kn</string>\r\n  <string>kk</string>\r\n  <string>km</" +
            "string>\r\n  <string>ko</string>\r\n  <string>ku</string>\r\n  <string>ky</string>\r\n  " +
            "<string>lo</string>\r\n  <string>la</string>\r\n  <string>lv</string>\r\n  <string>lt<" +
            "/string>\r\n  <string>lb</string>\r\n  <string>mk</string>\r\n  <string>mg</string>\r\n " +
            " <string>ms</string>\r\n  <string>ml</string>\r\n  <string>mt</string>\r\n  <string>mi" +
            "</string>\r\n  <string>mr</string>\r\n  <string>mn</string>\r\n  <string>my</string>\r\n" +
            "  <string>ne</string>\r\n  <string>no</string>\r\n  <string>ps</string>\r\n  <string>f" +
            "a</string>\r\n  <string>pl</string>\r\n  <string>pt</string>\r\n  <string>pa</string>\r" +
            "\n  <string>ro</string>\r\n  <string>ru</string>\r\n  <string>sm</string>\r\n  <string>" +
            "gd</string>\r\n  <string>sr</string>\r\n  <string>st</string>\r\n  <string>sn</string>" +
            "\r\n  <string>sd</string>\r\n  <string>si</string>\r\n  <string>sk</string>\r\n  <string" +
            ">sl</string>\r\n  <string>so</string>\r\n  <string>es</string>\r\n  <string>su</string" +
            ">\r\n  <string>sw</string>\r\n  <string>sv</string>\r\n  <string>tg</string>\r\n  <strin" +
            "g>ta</string>\r\n  <string>te</string>\r\n  <string>th</string>\r\n  <string>tr</strin" +
            "g>\r\n  <string>uk</string>\r\n  <string>ur</string>\r\n  <string>uz</string>\r\n  <stri" +
            "ng>vi</string>\r\n  <string>cy</string>\r\n  <string>xh</string>\r\n  <string>yi</stri" +
            "ng>\r\n  <string>yo</string>\r\n  <string>zu</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LangSource {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LangSource"]));
            }
            set {
                this["LangSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>af</string>\r\n  <string>sq</string>\r\n  <string>am</string>\r\n  <string>ar</s" +
            "tring>\r\n  <string>hy</string>\r\n  <string>az</string>\r\n  <string>eu</string>\r\n  <" +
            "string>be</string>\r\n  <string>bn</string>\r\n  <string>bs</string>\r\n  <string>bg</" +
            "string>\r\n  <string>ca</string>\r\n  <string>ceb</string>\r\n  <string>ny</string>\r\n " +
            " <string>zh-CN</string>\r\n  <string>co</string>\r\n  <string>hr</string>\r\n  <string" +
            ">cs</string>\r\n  <string>da</string>\r\n  <string>nl</string>\r\n  <string>en</string" +
            ">\r\n  <string>eo</string>\r\n  <string>et</string>\r\n  <string>tl</string>\r\n  <strin" +
            "g>fi</string>\r\n  <string>fr</string>\r\n  <string>fy</string>\r\n  <string>gl</strin" +
            "g>\r\n  <string>ka</string>\r\n  <string>de</string>\r\n  <string>el</string>\r\n  <stri" +
            "ng>gu</string>\r\n  <string>ht</string>\r\n  <string>ha</string>\r\n  <string>haw</str" +
            "ing>\r\n  <string>iw</string>\r\n  <string>hi</string>\r\n  <string>hmn</string>\r\n  <s" +
            "tring>hu</string>\r\n  <string>is</string>\r\n  <string>ig</string>\r\n  <string>id</s" +
            "tring>\r\n  <string>ga</string>\r\n  <string>it</string>\r\n  <string>ja</string>\r\n  <" +
            "string>jw</string>\r\n  <string>kn</string>\r\n  <string>kk</string>\r\n  <string>km</" +
            "string>\r\n  <string>ko</string>\r\n  <string>ku</string>\r\n  <string>ky</string>\r\n  " +
            "<string>lo</string>\r\n  <string>la</string>\r\n  <string>lv</string>\r\n  <string>lt<" +
            "/string>\r\n  <string>lb</string>\r\n  <string>mk</string>\r\n  <string>mg</string>\r\n " +
            " <string>ms</string>\r\n  <string>ml</string>\r\n  <string>mt</string>\r\n  <string>mi" +
            "</string>\r\n  <string>mr</string>\r\n  <string>mn</string>\r\n  <string>my</string>\r\n" +
            "  <string>ne</string>\r\n  <string>no</string>\r\n  <string>ps</string>\r\n  <string>f" +
            "a</string>\r\n  <string>pl</string>\r\n  <string>pt</string>\r\n  <string>pa</string>\r" +
            "\n  <string>ro</string>\r\n  <string>ru</string>\r\n  <string>sm</string>\r\n  <string>" +
            "gd</string>\r\n  <string>sr</string>\r\n  <string>st</string>\r\n  <string>sn</string>" +
            "\r\n  <string>sd</string>\r\n  <string>si</string>\r\n  <string>sk</string>\r\n  <string" +
            ">sl</string>\r\n  <string>so</string>\r\n  <string>es</string>\r\n  <string>su</string" +
            ">\r\n  <string>sw</string>\r\n  <string>sv</string>\r\n  <string>tg</string>\r\n  <strin" +
            "g>ta</string>\r\n  <string>te</string>\r\n  <string>th</string>\r\n  <string>tr</strin" +
            "g>\r\n  <string>uk</string>\r\n  <string>ur</string>\r\n  <string>uz</string>\r\n  <stri" +
            "ng>vi</string>\r\n  <string>cy</string>\r\n  <string>xh</string>\r\n  <string>yi</stri" +
            "ng>\r\n  <string>yo</string>\r\n  <string>zu</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LangTarget {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LangTarget"]));
            }
            set {
                this["LangTarget"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>af</string>\r\n  <string>sq</string>\r\n  <string>am</string>\r\n  <string>ar</s" +
            "tring>\r\n  <string>hy</string>\r\n  <string>az</string>\r\n  <string>eu</string>\r\n  <" +
            "string>be</string>\r\n  <string>bn</string>\r\n  <string>bs</string>\r\n  <string>bg</" +
            "string>\r\n  <string>ca</string>\r\n  <string>ceb</string>\r\n  <string>ny</string>\r\n " +
            " <string>zh-CN</string>\r\n  <string>co</string>\r\n  <string>hr</string>\r\n  <string" +
            ">cs</string>\r\n  <string>da</string>\r\n  <string>nl</string>\r\n  <string>en</string" +
            ">\r\n  <string>eo</string>\r\n  <string>et</string>\r\n  <string>tl</string>\r\n  <strin" +
            "g>fi</string>\r\n  <string>fr</string>\r\n  <string>fy</string>\r\n  <string>gl</strin" +
            "g>\r\n  <string>ka</string>\r\n  <string>de</string>\r\n  <string>el</string>\r\n  <stri" +
            "ng>gu</string>\r\n  <string>ht</string>\r\n  <string>ha</string>\r\n  <string>haw</str" +
            "ing>\r\n  <string>iw</string>\r\n  <string>hi</string>\r\n  <string>hmn</string>\r\n  <s" +
            "tring>hu</string>\r\n  <string>is</string>\r\n  <string>ig</string>\r\n  <string>id</s" +
            "tring>\r\n  <string>ga</string>\r\n  <string>it</string>\r\n  <string>ja</string>\r\n  <" +
            "string>jw</string>\r\n  <string>kn</string>\r\n  <string>kk</string>\r\n  <string>km</" +
            "string>\r\n  <string>ko</string>\r\n  <string>ku</string>\r\n  <string>ky</string>\r\n  " +
            "<string>lo</string>\r\n  <string>la</string>\r\n  <string>lv</string>\r\n  <string>lt<" +
            "/string>\r\n  <string>lb</string>\r\n  <string>mk</string>\r\n  <string>mg</string>\r\n " +
            " <string>ms</string>\r\n  <string>ml</string>\r\n  <string>mt</string>\r\n  <string>mi" +
            "</string>\r\n  <string>mr</string>\r\n  <string>mn</string>\r\n  <string>my</string>\r\n" +
            "  <string>ne</string>\r\n  <string>no</string>\r\n  <string>ps</string>\r\n  <string>f" +
            "a</string>\r\n  <string>pl</string>\r\n  <string>pt</string>\r\n  <string>pa</string>\r" +
            "\n  <string>ro</string>\r\n  <string>ru</string>\r\n  <string>sm</string>\r\n  <string>" +
            "gd</string>\r\n  <string>sr</string>\r\n  <string>st</string>\r\n  <string>sn</string>" +
            "\r\n  <string>sd</string>\r\n  <string>si</string>\r\n  <string>sk</string>\r\n  <string" +
            ">sl</string>\r\n  <string>so</string>\r\n  <string>es</string>\r\n  <string>su</string" +
            ">\r\n  <string>sw</string>\r\n  <string>sv</string>\r\n  <string>tg</string>\r\n  <strin" +
            "g>ta</string>\r\n  <string>te</string>\r\n  <string>th</string>\r\n  <string>tr</strin" +
            "g>\r\n  <string>uk</string>\r\n  <string>ur</string>\r\n  <string>uz</string>\r\n  <stri" +
            "ng>vi</string>\r\n  <string>cy</string>\r\n  <string>xh</string>\r\n  <string>yi</stri" +
            "ng>\r\n  <string>yo</string>\r\n  <string>zu</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LangSource_index {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LangSource_index"]));
            }
            set {
                this["LangSource_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>af</string>\r\n  <string>sq</string>\r\n  <string>am</string>\r\n  <string>ar</s" +
            "tring>\r\n  <string>hy</string>\r\n  <string>az</string>\r\n  <string>eu</string>\r\n  <" +
            "string>be</string>\r\n  <string>bn</string>\r\n  <string>bs</string>\r\n  <string>bg</" +
            "string>\r\n  <string>ca</string>\r\n  <string>ceb</string>\r\n  <string>ny</string>\r\n " +
            " <string>zh-CN</string>\r\n  <string>co</string>\r\n  <string>hr</string>\r\n  <string" +
            ">cs</string>\r\n  <string>da</string>\r\n  <string>nl</string>\r\n  <string>en</string" +
            ">\r\n  <string>eo</string>\r\n  <string>et</string>\r\n  <string>tl</string>\r\n  <strin" +
            "g>fi</string>\r\n  <string>fr</string>\r\n  <string>fy</string>\r\n  <string>gl</strin" +
            "g>\r\n  <string>ka</string>\r\n  <string>de</string>\r\n  <string>el</string>\r\n  <stri" +
            "ng>gu</string>\r\n  <string>ht</string>\r\n  <string>ha</string>\r\n  <string>haw</str" +
            "ing>\r\n  <string>iw</string>\r\n  <string>hi</string>\r\n  <string>hmn</string>\r\n  <s" +
            "tring>hu</string>\r\n  <string>is</string>\r\n  <string>ig</string>\r\n  <string>id</s" +
            "tring>\r\n  <string>ga</string>\r\n  <string>it</string>\r\n  <string>ja</string>\r\n  <" +
            "string>jw</string>\r\n  <string>kn</string>\r\n  <string>kk</string>\r\n  <string>km</" +
            "string>\r\n  <string>ko</string>\r\n  <string>ku</string>\r\n  <string>ky</string>\r\n  " +
            "<string>lo</string>\r\n  <string>la</string>\r\n  <string>lv</string>\r\n  <string>lt<" +
            "/string>\r\n  <string>lb</string>\r\n  <string>mk</string>\r\n  <string>mg</string>\r\n " +
            " <string>ms</string>\r\n  <string>ml</string>\r\n  <string>mt</string>\r\n  <string>mi" +
            "</string>\r\n  <string>mr</string>\r\n  <string>mn</string>\r\n  <string>my</string>\r\n" +
            "  <string>ne</string>\r\n  <string>no</string>\r\n  <string>ps</string>\r\n  <string>f" +
            "a</string>\r\n  <string>pl</string>\r\n  <string>pt</string>\r\n  <string>pa</string>\r" +
            "\n  <string>ro</string>\r\n  <string>ru</string>\r\n  <string>sm</string>\r\n  <string>" +
            "gd</string>\r\n  <string>sr</string>\r\n  <string>st</string>\r\n  <string>sn</string>" +
            "\r\n  <string>sd</string>\r\n  <string>si</string>\r\n  <string>sk</string>\r\n  <string" +
            ">sl</string>\r\n  <string>so</string>\r\n  <string>es</string>\r\n  <string>su</string" +
            ">\r\n  <string>sw</string>\r\n  <string>sv</string>\r\n  <string>tg</string>\r\n  <strin" +
            "g>ta</string>\r\n  <string>te</string>\r\n  <string>th</string>\r\n  <string>tr</strin" +
            "g>\r\n  <string>uk</string>\r\n  <string>ur</string>\r\n  <string>uz</string>\r\n  <stri" +
            "ng>vi</string>\r\n  <string>cy</string>\r\n  <string>xh</string>\r\n  <string>yi</stri" +
            "ng>\r\n  <string>yo</string>\r\n  <string>zu</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LangTarget_index {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LangTarget_index"]));
            }
            set {
                this["LangTarget_index"] = value;
            }
        }
    }
}
